### ISSUE TITLE
Alt+left/right key blocked

### ISSUE THREAD

**Issue by gobonja** [squalou/google-chat-linux#17]
When app is opened alt+left/right key are blocked, meaning back/forward navigation on any other app is not possible.

Tested with:
- package from aur
- version with electron7
- manually build package
- on plasma, budgie and deepin

Best regards

**Comment by squalou** [comment]
Hi,

sorry about that... guess what : I didn't even know that alt-left / right were used in this app.

It's incrediby slow and barely usable.

I'll probably disable it by default, and set an option to re-enable it.

By the way, you should give a try to the 'not electron7'  version, it moved to electron 9 which supposedly fixes the systray issues from electon 8. I'd be happy to have plasma / budgie / deepin feedback (if you have a few minutes to spare).

**Comment by gobonja** [comment]
@squalou 

I just tested new version and it's working perfectly!

If you need any more feedback feel free to ask.

btw. I am using electron9 version, I used electron7 just to test if issue is related to electron version.

Thanks for the quick fix.
