### ISSUE TITLE
2FA Google 'Card' not working since google-chat-linux-git-r27.8a4d6a1

### ISSUE THREAD

**Issue by TheLinuxNinja** [squalou/google-chat-linux#2]
Was unable to sign back in to Google after a password change since 2FA 'Card' doesn't follow link. had to downgrade to google-chat-linux-git-r27.8a4d6a1 to get this working.

Is this an issue with the electron update?

**Comment by squalou** [comment]
Damn, sorry about that.
USed to be fixed, borken again.
Issue is : there is an issue with electron that crashed when following some links.
So, there's some tricky guess to allow some an block others.

Obviously I block ne too much. Trying to fix asap

**Comment by squalou** [comment]
As a quick workaround : when needing to reconnect, just close the app and relauch it, from my tests it works.
Please tell me if it's the case for you.

In the meantime, still trying to enable links in these cards without breakig other links

**Comment by squalou** [comment]
Found a somewhat not so dirty fix that specifically leave alones the HTMLButtonElement, so that they beave natively.
Works for me, I hope tere aren't any side effects
