### ISSUE TITLE
after a few hours a popup "new version of google chat" comes up

### ISSUE THREAD

**Issue by druuhl** [squalou/google-chat-linux#22]
After a few hours running this client, there is a black popup in the left bottom corner with message

 - A new verion of Goolge Chat is available  [REFRESH]

clicking on refresh leads to google, clicking in the othere text let is disappear for a while. This broadcast is a bit annoying.

**Comment by squalou** [comment]
Damn :-(
the refresh "button" is a js action, I have no idea how to trap what's underneath.

**Comment by druuhl** [comment]
Evtl. an autoclick on the left side wich does not contain the link

**Comment by squalou** [comment]
I think I came up with something.
Try 0.5.7-3 : I just tested now, it worked for me. (sie effect of a solution to #23 : redirect all chat.google.com to self)

In case it's not fixed for you, reopen the issue.

https://github.com/squalou/google-chat-linux/releases/tag/0.5.7-3
