### ISSUE TITLE
 after a few hours a popup "new version of google chat" comes up part2

### ISSUE THREAD

**Issue by druuhl** [squalou/google-chat-linux#26]
After 

`
I think I came up with something.
Try 0.5.7-3 : I just tested now, it worked for me. (sie effect of a solution to #23 : redirect all chat.google.com to self)

In case it's not fixed for you, reopen the issue.

https://github.com/squalou/google-chat-linux/releases/tag/0.5.7-3
`

and some time of peace, this popup is back.

**Comment by squalou** [comment]
damn.
With the exact same behaviour I mean :
- you get the "new version bkahblah" message
- you click on it
- it gets you to your browser instead of staying in the app ?

No other redirections in between ?

**Comment by druuhl** [comment]
Argh, one stop more and i had not open this ticket. It moves away when i click on it. in the past version i thought it was gone. My fault, all its fine ;) THX

**Comment by squalou** [comment]
great to hear this !
