### ISSUE TITLE
Binary Versioning convention has changed

### ISSUE THREAD

**Issue by druuhl** [squalou/google-chat-linux#29]
The Versioning of the debian packages has change, i think this is wring

google-chat-linux_0.5.6-3_amd64.deb
google-chat-linux_0.5.7-3_amd64.deb
google-chat-linux_0.5.7-5_amd64.deb
google-chat-linux_5.11.9-1_amd64.deb  <----- should 0.5.11-9

**Comment by squalou** [comment]
Hi, 

check the README, it's on purpose ;-)

- dropped the meaningless "0"
- introduced electron version as second number

everything is under control :)
