### ISSUE TITLE
Google Chat is Crap thanks to Google

### ISSUE THREAD

**Issue by squalou** [squalou/google-chat-linux#35]
I know, I can do nothing about it : Google unleashed on May 5th 2021 a new version of Google Chat.

It was already a pile of crap before, I tried to address some issues with this standalone client.

Now it's getting worse.

Dear Google, go f... youself.

This client still works, but desktop notification / systray integration is useless, (theme also). I can't wait until the day I stop using this nonsense.

**Comment by ankurk91** [comment]
I can understand your frustration.

You can switch to my fork, which has fixed issues related to new UI. 

https://github.com/ankurk91/google-chat-electron

Hope you would like it 😅

**Comment by squalou** [comment]
Hi,

I'll have a look, for sure, thanks !

main issue is : beside notifications and themes etc ... I think the full UI is lame. 

It's not that I don't like changes, but these changes are a complete nonsense (not the place to discuss it at lenght, but seriousy they shoud hire people with ergonomic skills before rolling out new GUIs)

As long as my little tweak (Menu or Right click -> use old UI works, I'll stick to it.)


BTW : I've just noticed that commit / release in github did close the issue but without any comment taken from the PR or commit.

**Comment by squalou** [comment]
@ankurk91 thank you again : I've just learned how to deal properly with ipcRenderer, preload, etc... in order to have notifications work again AND with andbox and process isolation.

I hope you don't mind if I copied a file from your project almost as-is, I did mention your work and repo in the README.

I strongly feel like the day the 'old' UI will completely be removed by google I'll close this project and use yours :)

**Comment by ankurk91** [comment]
Glad that you are able to make your app working again. 😃

Keep an eye on this blog for announcements. 

https://workspaceupdates.googleblog.com/2021/03/new-and-improved-google-chat-ui-on-web.html?m=1

The old UI will be replaced with new UI soon.
