### ISSUE TITLE
Trying to add reaction (emoji) to a message freezes the application

### ISSUE THREAD

**Issue by stflink** [squalou/google-chat-linux#4]

**Comment by squalou** [comment]
Taht's weird.

I'm using it right now, without issue. Same thing as #3 ... very strange, so, same question : 

Do you use the .deb packaging,
If so, can you run 'from sources' using the 'build and run' instructions from readme ?

Personnaly I'm on archlinux, I don't have any easy way to test the .deb packaging. Maybe something is wrong there.

**Comment by stflink** [comment]
I have built and installed it like this:
npm run dist
dpkg -i dist/google-chat-linux_0.1.6-1_amd64.deb

Don't know why I haven't tried the most obvious way of installing/running it.

Seems to work perfectly using the 'build and run' instructions.
Thanks a lot for your efforts.

**Comment by squalou** [comment]
Thanks for your tests ! 
I'll probably update the README.md to state that the .deb packaging is 'untested' and may fail ;)

**Comment by stflink** [comment]
Well, it could very well be me not doing everything in a correct way when building. I did have to struggle to get all the tools and dependencies in place and I doubt I can retrace my steps at this point ;)
Anyway, thanks for maintaining this.
