### ISSUE TITLE
Tray Icon does not appear when using Waybar

### ISSUE THREAD

**Issue by SippieCup** [squalou/google-chat-linux#53]
Not sure exactly why as it works fine in i3.

Launching with `XDG_CURRENT_DESKTOP=Unity` or `XDG_CURRENT_DESKTOP= ` Does not resolve it.

![20220816_20h49m43s_grim](https://user-images.githubusercontent.com/679311/185009776-ad83b612-6b78-4d4f-b047-fc8b10b65a66.png)

Anyone know of a workaround or solution? otherwise closing the window just causes it to launch a new version every time. I'm sure this is more of an electron thing, just don't know how to resolve it.

**Comment by squalou** [comment]
Hm, interesting, I have personally no knowledge at all of waybar (but it looks great)

Tray icon relies on "appindicator" implementations, maybe you're missing one ?

In order to quit : Try `Ctrl Q`. this should always work.

**Comment by SippieCup** [comment]
`Ctrl Q` works, as does just throwing it into its own workspace,

ultimately though I ended up changing the .desktop to simply kill all the previous processes of google-chat-linux before opening a new one. That way I can close the window but still getting notifications when minimized. 

I think this stems from electron 15 + wayland & swaybar not working nicely together. I'm going to try updating it to electron 17 and see if that makes a difference as It would allow us to use Ozone to abstract the window system. Doubt it'll work though.

**Comment by SippieCup** [comment]
Figured it out. it was trying to use libappindicator3.so from the included stub files that were added for your left click fix.

Left clicking works fine without it, so maybe that is a legacy thing in electron 9->15 that was fixed? I can't reproduce on any DE, perhaps you need it for the fallback tray system?

I can make a pull request if you like, just know that besides testing left clicking, I really didn't test it well and was too lazy to make paths.js resolve correctly when using `npm start` just needs an environment toggle.

**Comment by squalou** [comment]
Interesting ! 
thank you for the investigation testing. 
It's always a good news to remove ugly old workarounds.

I'll try your version on my side (moved from xfce to gnome) and see if I see nothing weird and will merge it asap


thx !

**Comment by squalou** [comment]
@SippieCup 
so far so good, did a quick build and run from your code and it's working nicely.

Would you be so kind as to change version number in package.json from `5.15.17-1` to `5.20.18-1` ?

then, squash your commits and submit a PR, I'll be more than happy to merge it
