### ISSUE TITLE
[KDE] Tray icon shows up as a question mark when started with autostart

### ISSUE THREAD

**Issue by njanke96** [squalou/google-chat-linux#55]
I have the app installed through the AUR (google-chat-linux-bin version 5.20.18-1). On Plasma 5.25.5, I have the app configured to autostart through the system settings UI. Up until recently it has been starting fine but now it starts with this question mark icon in the system tray (3rd from the left):

![image](https://user-images.githubusercontent.com/12754124/189184700-ca5d2d7c-7b3e-4eab-8947-a778dea13b19.png)

The question mark does not change even if I get a message. When I quit the app and start it manually the icon is back to normal and updates when I get a message.

**Comment by squalou** [comment]
Damn,
I would bet it is related *again* to the appindicator tweak that was removed in last release.

When you manually start it you don't have the issue ?

**Comment by squalou** [comment]
good news,
not a perfect solution but good to know it helps

**Comment by squalou** [comment]
NOTE

you can also try to create theses empty files (they were removed in last release, as they cause issues with some other WM)

```
sudo touch /opt/google-chat-linux/libappindicator3.so
sudo touch /opt/google-chat-linux/libappindicator3.so.1
```

it may solve the issue
