### ISSUE TITLE
missing systray icon (KDE)

### ISSUE THREAD

**Issue by squalou** [squalou/google-chat-linux#56]
In case systray icon is not displayed correctly try this

```
sudo touch /opt/google-chat-linux/libappindicator3.so
sudo touch /opt/google-chat-linux/libappindicator3.so.1
```

**Comment by vwbusguy** [comment]
FWIW, the libappindicator.so hack didn't work for me for the icons showing up on Gnome, but I submitted a PR that fixes it for Gnome and perhaps might for KDE as well by happy accident?

**Comment by squalou** [comment]
Note : works for me with the workaround on Gnome :
- if using X.org
- under wayland ... provided I remove the `--ozone-platform-hint=auto` that I introduced too fast and removed since ;-)
