### ISSUE TITLE
Web Login Service doesn't work

### ISSUE THREAD

**Issue by jakobneef** [squalou/google-chat-linux#57]
My university is using a web login service where after entering our email we are redirected to a website where we have to enter our student id which is connected to a google account. This does not seem to work here, as after entering the mail address the app shows:
"
Web Login Service - Loading Session Information
Loading login session information from the browser...
"
But it does not actually open a browser to enter my credentials. 
Any advice would be greatly appreciated. 
Best,
Jakob

**Comment by squalou** [comment]
Hi,

can you try the workaround described in issu  #51  ?
(just in case)

**Comment by jakobneef** [comment]
That fixes. Sorry, I should have read the post more thoroughly.
Anyway, thanks for the quick answer!

**Comment by squalou** [comment]
you're welcome,

glad it works :)
