### ISSUE TITLE
[Feature] Css inject 

### ISSUE THREAD

**Issue by niksingh710** [squalou/google-chat-linux#62]
would be nice to give it a custom look.
[This](https://github.com/th-ch/youtube-music) project have that.

**Comment by squalou** [comment]
Hi,
once upon a time there was support for "custom theme". But google made it a pure nightmare, breaking it over and over. 

(se  #41 for the removal commit).

Maybe another approach could be tried,
you can try "Ferdium" I *think* they still support some sort of custom css in apps, maybe you'll be able to tweak google chat this way. If so, I'll even may be able to include it again.

Good luck if you try, reopen and let me know if you manage something ;-)

**Comment by ThatOneCalculator** [comment]
A simple CSS loader into the ASAR would be pretty appreciated, I'm working on a Rose Pine theme

**Comment by ThatOneCalculator** [comment]
This issue should be closed upon the next release
