### ISSUE TITLE
Monochrome tray icon

### ISSUE THREAD

**Issue by ThatOneCalculator** [squalou/google-chat-linux#75]
Most tray icons (on Linux, at least) have monochrome variants. 

ref: https://github.com/ipfs/ipfs-desktop/pull/2159

**Comment by squalou** [comment]
true enough.
Ideally the icone should inherit from current theme icon set.
(something I have no idea how to do but should probably be supported).

And only by default revert to current ones (which are google official ones)

**Comment by squalou** [comment]
add "iconTheme":"mono" in json config file starting from version 5.27.23-1.
New colored icons are supported too.
