### ISSUE TITLE
Electron 24 support ended

### ISSUE THREAD

**Issue by Luukvdm** [squalou/google-chat-linux#78]
[Support for Electron 24 ended](https://www.electronjs.org/docs/latest/tutorial/electron-timelines). I think it should be upgraded, but I find it to hard to tell how compatibility is with newer electron versions to create a PR.

**Comment by squalou** [comment]
Hi,
will try to find time to care of this.

Last time I checked it was - as often -- a real pain, with no benefit.

**Comment by squalou** [comment]
Ok I as wrong it seems smooth enough and brings better electron support. Expect a new release within the hour.
