### ISSUE TITLE
Move the "Apply theme" option to an app-specific Preference window

### ISSUE THREAD

**Issue by Deuchnord** [squalou/google-chat-linux#8]
The new option "Apply theme" is placed on top of the indicator menu. That’s quite annoying, because sometimes, I misclick it when I actually want to show the window.
Since this option is configuration-related, it would be great if this option were moved to a new app Preference window.

**Comment by squalou** [comment]
I understand, and beeing a total noo at UX design I value this feedback.

I'll see how to improve it s(hopefully shorly)

in the meantime, note that left click on the systray icon DOES show the window (no need to right click / Show). So, it's a kind of workaround

**Comment by squalou** [comment]
Right now,
I've changed the order of items, and added a separator

```
apply theme
--------------
force reload
show/hide
quit

```

Should help prevent missclick

**Comment by Deuchnord** [comment]
> in the meantime, note that left click on the systray icon DOES show the window (no need to right click / Show). So, it's a kind of workaround.

Actually, it does not on GNOME Shell, but it’s not related to your app (on GNOME, left click does not exist on indicators). It shows the menu instead.

> thing is, there's no really "app" space, it's just the google chat window being displayed in a browser. The only specific space _is_ the systray menu. Maybe I'll have to add a menu or something in he main app, which would use space. Not sure what is best.

Yes, but Google Chat for Linux acts exactly like an application. so you can perfectly add your own window that would take care of user preferences :)



> Right now,
> I've changed the order of items, and added a separator
> 
> ```
> apply theme
> --------------
> force reload
> show/hide
> quit
> ```
> 
> Should help prevent missclick

In my opinion, the items should be ordered in a way that the most used one is at the first place, and the less used one is at the lat place. So a more logical order would be:
1. Show/Hide
2. Force reload
3. Apply theme
4. (separator)
5. Quit

**Comment by squalou** [comment]
Didn't know for Gnome. I have friends using Gnome I'll try to test with them next time. From what I remember you had to add an extension on Gnome to have systray displayed, is it still the case ?

Not everyone uses the same menu entries, except for Quit which is mandatory for everyone. (frankly I never use the other ones except when debugging)

So, no problem, I reorder this.


One last question for your Gnome display : assuming you have the 'gnome bar' on top of the screen,
how does the systray display for now ? (what is on top, what on bottom)

On your example : 1. would be the top and 5. the bottom ?

**Comment by Deuchnord** [comment]
It currently looks like this:
![Screenshot](https://user-images.githubusercontent.com/7600265/68971635-45063d80-07ea-11ea-97d0-f207f4ea841d.png)

**Comment by squalou** [comment]
I've set it like this, I hope it's finefor a quick fix.
(finally, I leave the "force reload" ... in order to reload the 'hidden' window I've introduced to fix the systray color change, the reload may be needed when login back to the account )

![image](https://user-images.githubusercontent.com/4623644/69038249-b9f39600-09e9-11ea-8ce8-bb1e476d8553.png)

**Comment by Deuchnord** [comment]
Perfect, thanks! :smile:

**Comment by squalou** [comment]
Small step : added a custom menu that duplicate the systray options.

Main goal : for OS where systray is not available ... or else Quit is impossible :)

**Comment by squalou** [comment]
won't fix anything more about that, to be honest.
