### ISSUE TITLE
Everything is invisible after system upgrade

### ISSUE THREAD

**Issue by lgraziosi** [squalou/google-chat-linux#86]
Hello. Today I've updated some packages: [zypper_history.log](https://github.com/squalou/google-chat-linux/files/13675683/zypper_history.log).  
After this, google chat became unusable:
![image](https://github.com/squalou/google-chat-linux/assets/10742569/c1a4dee3-430a-46ed-b3fa-525d895e9024)
I can still click chats and stuff, but everything is invisible.

I'm using wayland on openSUSE 15.5. Kernel 5.14.21-150500.55.39.
Thanks.

**Comment by squalou** [comment]
Hi,

Maybe (probably not but ... maybe) it could be related to some cookies. I had other kind of issues recently after ogogle did updates on its side.

Try to remove directory $HOME/.config/google-chat-linux

Without success, you may want to try without Wayland juste for a check.

Also,
can you launch it from terminal and see what kind of errors would be displayed ? ( /usr/bin/google-chat-linux )

**Comment by lgraziosi** [comment]
Damn... it was the cache.
I took for granted that it was the wayland upgrade, but it was not!
Thank you, great software.
