### ISSUE TITLE
Task bar icon is always grey when online, notification problems

### ISSUE THREAD

**Issue by goferek** [squalou/google-chat-linux#87]
I am experiencing issues with the app that revolve around the visibility of the app icon and notification problems because of it. The app icon is consistently greyed out and doesn't show new notifications.
![image](https://github.com/squalou/google-chat-linux/assets/68773801/d449df0a-dc01-4b9e-9d9e-6b2c93ac6dbf)

**Comment by squalou** [comment]
hm, interesting issue, how do you launch the app ?

Can you try to launch it from terminal and see whatever errors might be logged ?

could be either icons that are not reachable (I may have botched the packages), or they exist but satus is not updated.

**Comment by goferek** [comment]
I got this from running google-chat-electron in console:

```Gtk-Message: 15:31:50.324: Failed to load module "xapp-gtk3-module"
Driver does not support the 0x46a6 PCI ID.
libGL error: failed to create dri screen
libGL error: failed to load driver: iris
Driver does not support the 0x46a6 PCI ID.
libGL error: failed to create dri screen
libGL error: failed to load driver: iris
(node:112783) DeprecationWarning: Got: "options.family" was never documented, please use "options.dnsLookupIpVersion"
(Use `google-chat-electron --trace-deprecation ...` to show where the warning was created)
[112880:1215/153150.427394:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
Driver does not support the 0x46a6 PCI ID.
[112783:1215/153152.145786:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented

**Comment by squalou** [comment]
Arf

guess what : I've just restarted mine to check the errors ... and now I have the same issue as you.

So : regarding the error messages you can ignore them (I don't have  graphical drivers ones, I have the last one, as usual)

My bet : Google dit AGAIN change things, like the name of the icons or whatever.

As I can reproduce it ... I bet I'll be able to find a way to detect new messages again ... hopefully. Stay tuned :)

**Comment by squalou** [comment]
see release  5.27.22-4

**Comment by goferek** [comment]
Installed the new release and it looks good :smiley: 
thanks for quick fix
